### PR TITLE
fix: reintroduce FetchFieldFromStruct as a public UDF

### PR DESCRIPTION
**Pull request by agavra**
### Description 

When upgrading from 5.3->5.4 commands that were already written into the command topic would fail with "Cannot find function FETCH_FEILD_FROM_STRCUT". The reason is that we made structs stop rewriting with that UDF and instead inlined it's usage and prevent people from using that function externally. This re-introduces the change into 5.4. so that upgrades are possible.

NOTE: This will not be merged to master and master will be considered a breaking upgrade from 5.4

### Testing done 

- verified the problem by running 5.3 and issuing a command with struct access
- upgraded to 5.4 and checked if it can recover; before this fix it cannot and after it can

### Reviewer checklist
- [ ] Ensure docs are updated if necessary. (eg. if a user visible feature is being added or changed).
- [ ] Ensure relevant issues are linked (description should include text like "Fixes #<issue number>")

### CODE REVIEW

**Comment by apurvam** [comment]
Here is the PR which removed `FETCH_FIELD_FROM_STRUCT` https://github.com/confluentinc/ksql/pull/3639

**Comment by agavra** [comment]
@apurvam - it was always special cased because unlike normal UDFs, `FETCH_FIELD_FROM_STRUCT` does not have a deterministic return type. The code introduced in this PR is manually cherry-picked (inverse) from https://github.com/confluentinc/ksql/pull/3639 (plus some additional tests)
