### ISSUE TITLE
Master branch fails to compile

### ISSUE THREAD

**Issue by satybald** [confluentinc/ksql#752]
The output of `mvn clean compile`

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project ksql-engine: Compilation failure: Compilation failure:
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java:[33,40] cannot find symbol
[ERROR] symbol:   class ValueMapperWithKey
[ERROR] location: package org.apache.kafka.streams.kstream
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java:[62,24] cannot find symbol
[ERROR] symbol:   class ValueMapperWithKey
[ERROR] location: class io.confluent.ksql.planner.plan.StructuredDataSourceNode
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java:[70,24] cannot find symbol
[ERROR] symbol:   class ValueMapperWithKey
[ERROR] location: class io.confluent.ksql.planner.plan.StructuredDataSourceNode
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java:[63,32] lambda expression not expected here
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java:[71,24] lambda expression not expected here
[ERROR] /home/ssatybaldiye/Documents/github/bigdata/ksql/ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java:[250,7] method mapValues in interface org.apache.kafka.streams.kstream.KStream<K,V> cannot be applied to given types;
[ERROR] required: org.apache.kafka.streams.kstream.ValueMapper<? super io.confluent.ksql.GenericRow,? extends VR>
[ERROR] found: (key,row)-[...]ow; }
[ERROR] reason: cannot infer type-variable(s) VR
[ERROR] (argument mismatch; incompatible parameter types in lambda expression)
[ERROR] -> [Help 1]
[ERROR] 
```

might be caused by #718

**Comment by satybald** [comment]
okey, after I deleted kafka-stream jar from local maven cache it compiled project without any errors. Just curious do you know how this confluent maven repository magic works? cc: @dguy @apurvam @hjafarpour

**Comment by big-andy-coates** [comment]
You probably just need to build using the `-U` switch to force updates of SNAPSHOT dependencies.

**Comment by satybald** [comment]
thanks, @big-andy-coates for a reply. yea, probably. the issue can be closed for now.
